import random
from dataclasses import dataclass
from datetime import date

from playwright.async_api import Page

from app.automation.navigation_discovery import _is_destructive
from app.core.enums import BugSeverity

_DISCOVER_FORMS_JS = """
() => {
    function cssPath(el) {
        if (el.id) return '#' + CSS.escape(el.id);
        const parts = [];
        let node = el;
        for (let depth = 0; depth < 6 && node && node.nodeType === 1 && node.tagName !== 'BODY'; depth++) {
            let part = node.tagName.toLowerCase();
            const parent = node.parentElement;
            if (parent) {
                const siblings = Array.from(parent.children).filter(c => c.tagName === node.tagName);
                if (siblings.length > 1) part += ':nth-of-type(' + (siblings.indexOf(node) + 1) + ')';
            }
            parts.unshift(part);
            node = parent;
        }
        return parts.join(' > ');
    }
    function fieldLabel(el) {
        if (el.id) {
            const lbl = document.querySelector('label[for="' + CSS.escape(el.id) + '"]');
            if (lbl) return lbl.textContent.trim();
        }
        const parentLabel = el.closest('label');
        return parentLabel ? parentLabel.textContent.trim() : '';
    }
    const forms = Array.from(document.querySelectorAll('form'));
    return forms.map(form => {
        const fields = Array.from(form.querySelectorAll('input, select, textarea'))
            .filter(el => {
                const style = getComputedStyle(el);
                return style.display !== 'none' && style.visibility !== 'hidden'
                    && el.type !== 'hidden' && !el.disabled && !el.readOnly;
            })
            .map(el => ({
                selector: cssPath(el),
                tag: el.tagName.toLowerCase(),
                type: el.type || 'text',
                name: el.name || '',
                placeholder: el.placeholder || '',
                label: fieldLabel(el),
            }));
        const submitEl = form.querySelector('button[type="submit"], input[type="submit"]')
            || Array.from(form.querySelectorAll('button')).find(b => !b.getAttribute('type') || b.getAttribute('type') === 'submit');
        const submit = submitEl
            ? { selector: cssPath(submitEl), text: (submitEl.textContent || submitEl.value || '').trim() }
            : null;
        const heading = form.closest('section, div') ? form.closest('section, div').querySelector('h1, h2, h3') : null;
        return {
            label: (heading && heading.textContent.trim()) || form.getAttribute('aria-label') || form.getAttribute('name') || 'Form',
            fields,
            submit,
        };
    }).filter(f => f.fields.length > 0).slice(0, 5);
}
"""

_FEEDBACK_JS = """
() => {
    const text = document.body.innerText.toLowerCase();
    const hasMessage = /success|thank you|submitted|error|invalid|required|failed|saved|confirmed|received/.test(text)
        || !!document.querySelector('[role="alert"], [class*="toast" i], [class*="error" i], [class*="success" i]');
    return { hasMessage };
}
"""


def _fake_value(field: dict) -> str | None:
    input_type = (field.get("type") or "text").lower()
    hint = f"{field.get('name', '')} {field.get('placeholder', '')} {field.get('label', '')}".lower()

    if input_type in ("checkbox", "radio", "file", "color", "range"):
        return None
    if input_type == "email" or "email" in hint:
        return f"visionqa.test+{random.randint(1000, 9999)}@example.com"
    if input_type == "tel" or "phone" in hint:
        return "+1 555 0100"
    if input_type == "password":
        return "VisionQA-Test-1!"
    if input_type == "number":
        return "42"
    if input_type == "date":
        return date.today().isoformat()
    if input_type == "url" or "website" in hint:
        return "https://example.com"
    if "zip" in hint or "postal" in hint:
        return "94103"
    if "city" in hint:
        return "San Francisco"
    if "address" in hint:
        return "123 Test Street"
    if "phone" in hint:
        return "+1 555 0100"
    if field.get("tag") == "textarea" or "message" in hint or "comment" in hint:
        return "This is a test message generated by an automated VisionQA scan."
    if "name" in hint and "user" not in hint:
        return "Jane Doe"
    return "Test Value"


@dataclass
class FormInteractionResult:
    form_label: str
    fields_total: int
    fields_filled: int
    submitted: bool
    outcome: str


class InteractionEngine:
    """Detects forms, fills them with realistic fake data, and — only when
    explicitly enabled — submits non-destructive forms and checks for
    feedback. Filling is always safe/reversible; submission creates real
    data in the target app, so it stays opt-in (see Scan.fill_forms)."""

    async def run(self, page: Page, page_url: str, allow_submit: bool) -> tuple[list[FormInteractionResult], list[dict]]:
        try:
            forms = await page.evaluate(_DISCOVER_FORMS_JS)
        except Exception:
            return [], []

        results: list[FormInteractionResult] = []
        bugs: list[dict] = []

        for form in forms:
            filled = 0
            for f in form["fields"]:
                value = _fake_value(f)
                if value is None:
                    continue
                try:
                    if f["tag"] == "select":
                        await page.select_option(f["selector"], index=1, timeout=3000)
                    else:
                        await page.fill(f["selector"], value, timeout=3000)
                    filled += 1
                except Exception:
                    continue

            submit = form.get("submit")
            submitted = False
            outcome = "filled_only"

            if filled == 0:
                outcome = "no_fillable_fields"
            elif not submit:
                outcome = "no_submit_control"
            elif not allow_submit:
                outcome = "filled_only"
            elif _is_destructive(submit.get("text", "")):
                outcome = "skipped_destructive"
            else:
                try:
                    before_url = page.url
                    await page.click(submit["selector"], timeout=5000)
                    await page.wait_for_timeout(1200)
                    submitted = True
                    outcome = "submitted"
                    feedback = await page.evaluate(_FEEDBACK_JS)
                    if not feedback.get("hasMessage") and page.url == before_url:
                        bugs.append({
                            "severity": BugSeverity.MEDIUM.value,
                            "title": "Form submitted with no visible feedback",
                            "component": "Form",
                            "description": f'Submitting "{form.get("label", "form")}" produced no success/error '
                                           f"message and no navigation — users can't tell if it worked.",
                            "selector": submit["selector"],
                            "page_url": page_url,
                            "fix_suggestion": "Show a toast, inline message, or redirect after form submission.",
                        })
                except Exception:
                    outcome = "submit_failed"

            results.append(FormInteractionResult(
                form_label=form.get("label", "form"),
                fields_total=len(form["fields"]),
                fields_filled=filled,
                submitted=submitted,
                outcome=outcome,
            ))

        return results, bugs
